var GAME_LEVELS = [
    ["                                                                                ",
     "                                                                                ",
     "                                                                                ",
     "                                                                                ",
     "                                                                                ",
     "                                                                                ",
     "                                                                  xxx        x  ",
     "                                                      |||        xx!xx       x  ",
     "                                                                 x!!!x       x  ",
     "                                                                 xx!xx       x  ",
     "                        b          xxxx                           xvx        x  ",
     "                       xxx                                                   x  ",
     "  xx                                                                         x  ",
     "  x                                                                          x  ",
     "  x                                     xxxx                             o   x  ",
     "  x          xx               xxxx                                      xx   x  ",
     "  x  @       x        xxxxx                                                  x  ",
     "  xxxxxxxxxxxx                                    xxx                        x  ",
     "             x                                                               x  ",
     "             x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
     "             x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
     "             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
     "                                                                                ",
     "                                                                                "],
  ["                                      x!!x                    o                                              x!x  ",
   "                                      x!!x                                                                   x!x  ",
   "                                      x!!xxxxxxxxxx                                                          x!x  ",
   "                                      xx!!!!!!!!!!xx                                                         x!x  ",
   "                                       xxxxxxxxxx!!x                                                         x!x  ",
   "                                                xx!x                                                         x!x  ",
   "                                                 x!x                                                        x!!x  ",
   "                                                 xvx                                    x!!!!!!!!!!!!!!!!!!!!!xx  ",
   "                                                                         xx       b     x!xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!!!!!!!xx      v                        ",
   "                                                               xxxxxxxxxxxxxxxxxxx                                ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                            xx                    ",
   "                                                                                             x                    ",
   "                                                                                      xx     x                    ",
   "                                                                                             x                    ",
   "                                                             xxx                             x                    ",
   "             xx        xx                           xx                                       x                    ",
   "     @                                                                                       x                    ",
   "    xxx                                                                  xxx               xxx                    ",
   "    x x                                                              x                       x      |||           ",
   "!!!!x x!!!!!!xxxxxxxxxxx!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     xxx         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx       xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x                      xx!!!!!!xx !                    x       x                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                            !          !                                      ",
   "                                                            !          !                                      ",
   "                                                            !          !                                      ",
   "                                                xxx        !!!        !!!                                     ",
   "                                                           !!!        !!!                                     ",
   "                                                           xxxv       xxxv                                    ",
   "                                         xx                 x          x                                      ",
   "                                                            x   ||||   x                                      ",
   "                                                            x          x                                      ",
   "                                                            xx xxxxxxxxx                                      ",
   "                                     xx                     x                                                 ",
   "                                      x        xxxx   xxxxxxx                                                 ",
   "                                      x               x     o                                                 ",
   "                                      x        b      x                                                       ",
   "                                      x xx    xx      x                                                       ",
   "                                      x = = =         x                                                       ",
   "                                            x         x                                                       ",
   "                                 x               = = =x                        x                              ",
   "                                      x               x                       xxx                             ",
   "                                     xxx              x          xx                                           ",
   "                                                      x                 xxx                                   ",
   "                                        xxx           x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                       ",
   "                                                      x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                       ",
   "                                                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!                       ",
   "                                             x                     xxxx               !                       ",
   "  xxx                                              xxx             xxxx               !                    x  ",
   "  x x                                    xx                        xxxx               !                    x  ",
   "  x                                      xx                        xxxx               !                    x  ",
   "  x                                    xxxx                        xxxx               !                    x  ",
   "  x                                    xxxx                        xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  x                                  xxxxxx                        xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  x                                  xxxxxx                        xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  x                                xxxxxxxx                        xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  x                                xxxxxxxx                        xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  x                           xxxxxxxxxxxxx                        xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  x      @                    x           x!!!!!!!!!!!!!!!!!!!!!!!!xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                    xx        ",
   "                                                                                                   xx         ",
   "                                                                                                  xx          ",
   "                                                                                                  x           ",
   "                                                                                                b x           ",
   "                                                                                                x xo          ",
   "                                                                                                  xxx         ",
   "                                                                                                          xx  ",
   "                     x                                                                      x                 ",
   "       x     x                x                                                       x                       ",
   "       x=    x                                                               xxxx                             ",
   "       x ||| x                                                    xx                                          ",
   "                                                                                                              ",
   "                                                                                        x                     ",
   "                           x                               xx                                                 ",
   "                                                                                                              ",
   "                                                                                      x            xx         ",
   "                                                                                          xx                  ",
   "                    x                                      xx                                  xx             ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                 xx                                           ",
   "                           x                                              x        x                          ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  xxxxxxxxx                       x                                                                           ",
   "  x                                                                                                           ",
   "  x                                                                                                           ",
   "  x  @        xxx                   xxx                                                                       ",
   "  xxxxxxx                                     xxxxx                                                           ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
  ["    x   x xxxxx x   x        ",
   "    x   x x   x x   x        ",
   "    xxxxx x   x x   x        ",
   "      x   x   x x   x        ",
   "      x   xxxxx xxxxx        ",
   "                             ",
   "  x    x    x x x   x  !     ",
   "   x  x x  x  x xx  x  !     ",
   "    xx   xx   x x x x        ",
   "     x   x    x x  xx  !     ",
   "                             ",
   "                             "]

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
